version: '3'
services:
  db:
    image: postgres:11
    restart: always
    container_name: db_golang
    env_file: .env
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  # api:
  #   build: .
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   container_name: api
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/db_golang
  #   links:
  #     - db
  #   depends_on:
  #     - db

volumes:
  postgres: